=== nwoki/2s2h-website/cgi-bin/login.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://www.2s2h.com"
xmlns="http://www.2s2h.com"
elementFormDefault="unqualified">

<xsd:element name="users">
  <xsd:complexType>
    <xsd:sequence minOccurs="0" maxOccurs="unbounded">
      <xsd:element ref="user"/>
    </xsd:sequence>  
  </xsd:complexType>
</xsd:element>

<xsd:element name="user">
  <xsd:complexType>
    <xsd:sequence>
      <xsd:element name="name" type="xsd:string"/>
      <xsd:element name="surname" type="xsd:string"/>
      <xsd:element name="email" type="xsd:string"/>
      <xsd:element name="nick" type="xsd:string"/>
      <xsd:element name="password" type="xsd:string"/>
    </xsd:sequence>
  </xsd:complexType>
</xsd:element>

</xsd:schema>

=== nwoki/2s2h-website/cgi-bin/logins.xml
<?xml version="1.0"?>
<users
xmlns="http://www.2s2h.com"
xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance"
xsd:schemaLocation="http://www.2s2h.com login.xsd">
  <user>
    <name>Andrej</name>
    <surname>kaplosky</surname>
    <email>and@elis.it</email>
    <nick>prok</nick>
    <password>asfdasd</password>
  </user>
  <user>
    <name>Kevin</name>
    <surname>Luprois</surname>
    <email>port@elis.it</email>
    <nick>Alies</nick>
    <password>acfsd</password>
  </user>
</users>
