=== nwoki/2s2h-website/cgi-bin/newsDB.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://www.2s2h.com"
    xmlns="http://www.2s2h.com"
    elementFormDefault="qualified">

    <xsd:element name="news">
        <xsd:complexType>
            <xsd:sequence minOccurs="0" maxOccurs="unbounded">
                <xsd:element ref="article"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="article">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="title" type="xsd:string"/>
                <xsd:element name="date" type="xsd:date"/>
                <xsd:element name="body" type="xsd:string"/>
                <xsd:element name="author" type="xsd:string"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== nwoki/2s2h-website/http/newsDB.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="newsReader.xsl"?><news xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:schemaLocation="http://www.2s2h.com newsDB.xsd">
  <article id="1">
    <title>prova</title>
    <date>2010-05-10</date>
    <body><![CDATA[Questa e' la prima news di prova]]></body>
    <author>zamy</author>
  </article>
  <article id="2">
    <title>Uscita nuova versione del gioco!</title>
    <date>2010-05-12</date>
    <body><![CDATA[E' finalmente uscita la versione 4.2 del gioco Urban Terror! 
Nuove grafiche, nuovi effetti (come quello per l'acqua... da vedere!) e tanto altro.

Lo potete scaricare dal sito ufficiale :)]]></body>
    <author>n3m3s1s</author>
  </article>
  <article id="3">
    <title>Auguri nemesis!</title>
    <date>2010-06-20</date>
    <body><![CDATA[ Il Capo del nostro clan compie 23 anni!Fortuna che non ha ancora intenzione di farsi una famiglia e ha tempo da perdere con noi]]></body>
    <author>Revan</author>
  </article>
</news>
